# Generated by Django 2.1.5 on 2019-02-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_site', '0003_remove_courses_lesson_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Amath',
            field=models.FloatField(max_length=100, null=True, verbose_name='高等数学'),
        ),
        migrations.AlterField(
            model_name='users',
            name='C',
            field=models.FloatField(max_length=100, null=True, verbose_name='C语言'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Cpp',
            field=models.FloatField(max_length=100, null=True, verbose_name='C++'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Lalg',
            field=models.FloatField(max_length=100, null=True, verbose_name='线性代数'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Uphy',
            field=models.FloatField(max_length=100, null=True, verbose_name='大学物理'),
        ),
    ]
